@ECHO OFF

REM
REM	(C) SOFT DATA S.A. (Ene 1993)
REM	SDCLASS (Sistema de Avisos Clasificados)
REM
REM	Sets for Data Bases Path Names
REM

REM	Paths of Datas Bases Modified during operation
REM	Classified Ads Data Bases (read-write)
SET SDC_A=H:\SDCLASS\BASES_A\

REM	Configuration Data Bases (read-write)
SET SDC_B=H:\SDCLASS\BASES_B\

REM	Paths of Data Bases Not Modified during operation
REM	Data Bases with only Configuration Datas (Read only)
SET SDC_C=H:\SDCLASS\BASES_C\

REM	Paths of Data Bases for Credit Control module ( read-write )
SET SDC_X=H:\SDCLASS\BASES_X\

REM	Paths of Data Bases for Historical Backups On-line
REM	(read-write)
SET SDC_Z=H:\SDCLASS\BASES_Z\

REM	Path of Data Bases for Historical Backups Off-line
REM	(read-write)
SET SDC_ZZ=C:\SDCLASS\BASES_ZZ\

REM	Path for Temporary Files Generation
REM	(read-write)
SET SDC_T=C:\SDCLASS\




REM	End of File
